#debug=true
spring.main.banner-mode=off
hibernate.types.print.banner=false

spring.cloud.gcp.config.enabled=true
spring.cloud.gcp.logging.enabled=true
spring.cloud.gcp.trace.enabled=true
spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.core.enabled=true

spring.cloud.gcp.sql.instance-connection-name=GCP_PROJECT:REGION:INSTANCE_NAME
spring.cloud.gcp.sql.database-name=DB_NAME

spring.datasource.username=SOME_USERNAME
spring.datasource.password=SOME_PASSWORD

gcp.creds.provider=gcpDefault
audiofiles.storage=gcsWrite
gcs.audiofiles.bucket=paper-time/paper-audio

### START: TTS Settings ####
tts.speaking.rate.float=0.85
### END: TTS Settings ####

# Default no. of papers to process per category, during an end-to-end data refresh
data.refresh.papers.count=50

# Logback config
# Ref: http://logback.qos.ch/manual/layouts.html
logging.level.audiogen=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{5} - %msg%n

## Disable security for Spring Boot actuator endpoints
#management.security.enabled=false
#management.endpoints.web.exposure.include=mappings