#name: Deploy to Google App Engine
#on:
#  push:
#    branches:
#      - prod-deploy
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: push to JFrog
#        uses: jfrog/setup-jfrog-cli@v1.2.0
#        env:
#          JF_ARTIFACTORY_1: ${{ secrets.JFROG_KEY }}
#      - run: |
#          jfrog rt mvn clean test deploy
